version: "3.8"
services:
    web:
        image: venceslav82/bgapp-web
        deploy:
            replicas: 5
        ports:
            - 8000:80
        volumes:
            - "/home/vagrant/hw4/hw4/web:/var/www/html:ro"
        networks:
            - app-network
    db:
        image: venceslav82/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network:
